### ISSUE TITLE
v3 - potentially remove mirrors dependency?

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/jael#43]
*This issue was automatically moved to: https://github.com/angel-dart/angel/issues/148.

**Comment by tabula-rasa** [comment]
Hi @thosakwe, love your work! Any plans on working on this issue? :)

**Comment by thosakwe** [comment]
It is very low on the list of priorities. The reason for the `dart:mirrors` dependency is being able to resolve `object.property` expressions.

A potential pull request could separate this functionality from the `MemberExpression` class and put it in the `JaelRenderer` class (which would also require passing the `JaelRenderer` instance to all `JaelExpression`s when they compute their values).

I can't imagine many situations where you'd really want to disable this, though, as it would kind of defeat the purpose of a dynamic templating language like Jael. Of course, there are infinite ways to render templates without Jael, especially if yours are more static in nature.
